from dataclasses import dataclass
from dataclasses import field
from datetime import datetime
from functools import cached_property
from importlib import resources
from pathlib import Path
from pip_requirements_parser import RequirementsFile  # type: ignore
from plonex.base import BaseService
from rich.console import Console
from tempfile import NamedTemporaryFile
from urllib.parse import urljoin
from urllib.parse import urlparse

import re
import requests
import sh  # type: ignore[import-untyped]
import tomllib


def name_as_pep503(name: str) -> str:
    """Return a package name that is compatible with PEP 503"""
    return re.sub(r"[-_.]+", "-", name).lower()


@dataclass(kw_only=True)
class InstallService(BaseService):

    name: str = "install"
    dont_ask: bool = False

    etc_folder: Path = field(init=False)
    tmp_folder: Path = field(init=False)
    var_folder: Path = field(init=False)

    requirements_d_folder: Path = field(init=False)
    constraints_d_folder: Path = field(init=False)
    requirements_txt: Path = field(init=False)
    constrainst_txt: Path = field(init=False)

    @cached_property
    def options_defaults(self) -> dict:
        options_defaults = super().options_defaults
        options_defaults["plone_version"] = "6.1-latest"
        options_defaults["plonex_base_constraint"] = (
            "https://dist.plone.org/release/{{ plone_version }}/constraints.txt"
        )
        return options_defaults

    def __post_init__(self):
        self.target = self._ensure_dir(self.target.absolute())
        self.etc_folder = self._ensure_dir(self.target / "etc")
        self.tmp_folder = self._ensure_dir(self.target / "tmp")
        self.var_folder = self._ensure_dir(self.target / "var")
        self.requirements_d_folder = self._ensure_dir(
            self.etc_folder / "requirements.d"
        )
        self.constraints_d_folder = self._ensure_dir(self.etc_folder / "constraints.d")

    @property
    def default_python(self):
        """Check with python executable is available"""
        if "python" in self.options:
            return self.options["python"]

        for python in ["python3", "python"]:
            try:
                return self.execute_command(["which", python]).strip()
            except sh.ErrorReturnCode:
                continue

    def ensure_virtualenv(self):
        """Ensure that we have a virtualenv"""
        if not (self.target / ".venv" / "bin" / "activate").exists():
            if self.options.get("python") or self.dont_ask:
                python_path = self.default_python
            else:
                console = Console()
                python_path = (
                    console.input(
                        f"Please select the Python executable "
                        f"(default: {self.default_python}): "
                    )
                    or self.default_python
                )
            self.logger.info("Creating a virtualenv")
            self.execute_command(
                [str(python_path), "-m", "venv", str(self.target / ".venv")]
            )

        if not (self.virtualenv_dir / "bin" / "uv").exists():
            self.logger.info("Installing uv")
            self.execute_command(
                [
                    str(self.virtualenv_dir / "bin" / "pip"),
                    "install",
                    "uv",
                ]
            )

    @BaseService.entered_only
    def add_packages(self, packages: list):
        """Add a list of packages to the requirements"""
        now = datetime.now()
        time_marker = now.strftime("%Y%m%d-%H%M%S")
        lines = [
            "# Packages added by plonex install",
        ]
        lines.extend(sorted(packages))
        (self.requirements_d_folder / f"999-add-package-{time_marker}.txt").write_text(
            "\n".join(lines) + "\n"
        )

    @BaseService.entered_only
    def install_package(self, package: str):
        """Install a package in the virtualenv respecting the constraints"""
        self.ensure_virtualenv()
        self.logger.info("Installing %r", package)
        command = [
            str(self.virtualenv_dir / "bin" / "uv"),
            "pip",
            "install",
            package,
            "-c",
            str(self.constrainst_txt.absolute()),  # type: ignore
        ]
        self.execute_command(command)

    def make_requirements_txt(self):
        """This will merge the requirements files in one big requirements.txt file"""
        lines = []
        for file in sorted(self.requirements_d_folder.iterdir()):
            lines.append(f"-r {file.absolute()}")
        self.requirements_txt = self.var_folder / "requirements.txt"
        with open(self.requirements_txt, "w") as file:
            file.write("# This file is generated by plonex\n")
            file.write("\n".join(lines))

    def resolve_package_name_from_path(self, requirement) -> str:
        """Resolve the package name from a path"""
        path = Path(requirement.link.path)

        pyproject_toml = path / "pyproject.toml"
        if pyproject_toml.exists():
            pyproject = tomllib.loads(pyproject_toml.read_text())

            try:
                return pyproject["project"]["name"]
            except KeyError:
                try:
                    return pyproject["tool"]["poetry"]["name"]
                except KeyError:
                    pass

        setup_cfg_path = path / "setup.cfg"
        if setup_cfg_path.exists():
            # This is deprecated
            from setuptools.config import read_configuration

            config = read_configuration(str(setup_cfg_path))
            try:
                return config["metadata"]["name"]
            except KeyError:
                pass

        return path.absolute().name

    def developed_packages(self) -> set[str]:
        """Try to understand which packages are under development"""
        packages = set()
        for file in self.requirements_d_folder.iterdir():
            requirements = RequirementsFile.from_file(str(file), include_nested=True)
            editable_requirements = (
                requirement
                for requirement in requirements.requirements
                if requirement.is_editable
            )
            for requirement in editable_requirements:
                try:
                    name = self.resolve_package_name_from_path(requirement)
                except Exception as e:
                    name = requirement.link.filename
                    self.logger.info(
                        "Could not resolve package name for requirement %r: %s",
                        requirement,
                        e,
                    )

                packages.add(name_as_pep503(name))
        return packages

    def developed_packages_and_paths(self) -> set[str]:
        """Try to understand which packages are under development"""
        packages = set()
        for file in self.requirements_d_folder.iterdir():
            requirements = RequirementsFile.from_file(str(file), include_nested=True)
            editable_requirements = (
                requirement
                for requirement in requirements.requirements
                if requirement.is_editable
            )
            for requirement in editable_requirements:
                try:
                    name = self.resolve_package_name_from_path(requirement)
                except Exception as e:
                    name = requirement.link.filename
                    self.logger.info(
                        "Could not resolve package name for requirement %r: %s",
                        requirement,
                        e,
                    )
                packages.add(
                    f"{name_as_pep503(name)} → {Path(requirement.link.path).absolute()}"
                )
        return packages

    def make_constraints_txt(self):
        """Merge the constraints files in one big constraints.txt file"""
        developed_packages = self.developed_packages()
        included_files = []
        plonex_base_constraint = self.plonex_base_constraint
        if plonex_base_constraint:
            included_files.append(f"-c {plonex_base_constraint}")
        constraints = {}
        for file in sorted(self.constraints_d_folder.iterdir()):
            if file == self.legacy_constraints_file:
                continue
            file_includes, file_constraints = self._collect_constraint_entries(
                file,
                developed_packages=developed_packages,
                expand_remote_includes=False,
            )
            for include_line in file_includes:
                if include_line not in included_files:
                    included_files.append(include_line)
            for key, requirement in file_constraints.items():
                if key not in constraints:
                    constraints[key] = requirement

        merged_constraints = included_files + [
            requirement.dumps() for _, requirement in sorted(constraints.items())
        ]

        self.constrainst_txt = self.var_folder / "constraints.txt"

        with open(self.constrainst_txt, "w") as file:
            file.write("# This file is generated by plonex\n")
            file.write("\n".join(merged_constraints))

    @cached_property
    def plonex_base_constraint(self) -> str | Path | None:
        raw_source = self.options.get("plonex_base_constraint")
        if not raw_source:
            return None

        if not isinstance(raw_source, str):
            return raw_source

        if raw_source.startswith("resource://"):
            source_path = raw_source.partition("resource://")[2]
            package, filename_path = source_path.partition(":")[::2]
            return Path(str(resources.files(package) / filename_path)).resolve()

        if self._is_remote_requirement_source(raw_source):
            return raw_source

        path = Path(raw_source).expanduser()
        if path.is_absolute():
            return path.resolve()
        return (self.target / path).resolve()

    @staticmethod
    def _is_remote_requirement_source(source: str | Path) -> bool:
        if isinstance(source, Path):
            return False
        return urlparse(source).scheme in {"http", "https"}

    def _resolve_requirement_source(
        self,
        reference: str,
        base_source: str | Path,
    ) -> str | Path:
        reference_path = Path(reference).expanduser()
        if reference_path.is_absolute() or self._is_remote_requirement_source(
            reference
        ):
            return reference

        if isinstance(base_source, Path):
            return (base_source.parent / reference_path).resolve()
        return urljoin(base_source, reference)

    def _parse_requirement_source(self, source: str | Path):
        if not self._is_remote_requirement_source(source):
            return RequirementsFile.from_file(str(source), include_nested=False)

        remote_source = str(source)
        response = requests.get(remote_source, timeout=30)
        response.raise_for_status()
        with NamedTemporaryFile(
            mode="w",
            suffix=".txt",
            dir=self.tmp_folder,
            delete=False,
        ) as handle:
            handle.write(response.text)
            tmp_name = handle.name
        try:
            return RequirementsFile.from_file(tmp_name, include_nested=False)
        finally:
            Path(tmp_name).unlink(missing_ok=True)

    def _collect_constraint_entries(
        self,
        source: str | Path,
        developed_packages: set[str] | None = None,
        seen: set[str] | None = None,
        expand_remote_includes: bool = True,
    ):
        if seen is None:
            seen = set()

        source_key = str(source.resolve()) if isinstance(source, Path) else source
        if source_key in seen:
            return [], {}
        seen.add(source_key)

        parsed = self._parse_requirement_source(source)
        included_files: list[str] = []
        constraints = {}

        for option in getattr(parsed, "options", []):
            for option_name, flag in (("constraints", "-c"), ("requirements", "-r")):
                for reference in option.options.get(option_name, []):
                    resolved = self._resolve_requirement_source(reference, source)
                    if self._is_remote_requirement_source(resolved):
                        include_line = f"{flag} {resolved}"
                        if include_line not in included_files:
                            included_files.append(include_line)
                        if not expand_remote_includes:
                            continue

                    nested_includes, nested_constraints = (
                        self._collect_constraint_entries(
                            resolved,
                            developed_packages=developed_packages,
                            seen=seen,
                            expand_remote_includes=expand_remote_includes,
                        )
                    )
                    for include_line in nested_includes:
                        if include_line not in included_files:
                            included_files.append(include_line)
                    for key, requirement in nested_constraints.items():
                        if key not in constraints:
                            constraints[key] = requirement

        for requirement in parsed.requirements:
            name = getattr(requirement, "name", None)
            if not name:
                continue
            normalized_name = name_as_pep503(str(name))
            key = (normalized_name, str(requirement.marker))
            if developed_packages is not None and normalized_name in developed_packages:
                continue
            if key not in constraints:
                constraints[key] = requirement

        return included_files, constraints

    @staticmethod
    def _normalize_requirement_dump(requirement) -> str:
        return requirement.dumps().lower().replace("_", "-")

    @staticmethod
    def _requirement_key(requirement) -> str | None:
        name = getattr(requirement, "name", None)
        if not name:
            return None
        return name_as_pep503(str(name))

    @property
    def command(self):
        return [
            str(self.virtualenv_dir / "bin" / "uv"),
            "pip",
            "install",
            "-r",
            str(self.requirements_txt.absolute()),
            "-c",
            str(self.constrainst_txt.absolute()),
        ]

    def __enter__(self):
        super().__enter__()
        self.ensure_virtualenv()
        self.make_requirements_txt()
        self.make_constraints_txt()
        return self

    @BaseService.entered_only
    def run(self, save_constraints: bool = False):
        # Check if we have a virtualenv and if not create one
        self.ensure_virtualenv()
        super().run()
        # Run pip freeze and compare the output with the constraints
        # to see if we are missing something
        self.logger.debug("Checking if all constraints are met")

        _, merged_constraints = self._collect_constraint_entries(self.constrainst_txt)
        constraints = list(merged_constraints.values())
        installed = self.execute_command(
            [str(self.virtualenv_dir / "bin" / "pip"), "freeze"]
        )

        # Save the installed packages to a temporary file
        with open(self.tmp_folder / "installed.txt", "w") as file:  # type: ignore
            file.write(installed)

        installed = RequirementsFile.from_file(file.name).requirements

        constrained_names = {
            key for req in constraints if (key := self._requirement_key(req))
        }
        constrained_dumps = {
            self._normalize_requirement_dump(req) for req in constraints
        }

        missing = set()
        for requirement in installed:
            requirement_dump = self._normalize_requirement_dump(requirement)
            if requirement_dump.startswith("--editable"):
                continue

            requirement_key = self._requirement_key(requirement)
            if requirement_key and requirement_key in constrained_names:
                continue
            if requirement_dump in constrained_dumps:
                continue
            missing.add(requirement_dump)

        if missing:
            if save_constraints:
                now = datetime.now().strftime("%Y%m%d-%H%M%S")
                autoinstalled_file = (
                    self.target
                    / "etc"
                    / "constraints.d"
                    / f"999-{now}-autoinstalled.txt"
                )
                if autoinstalled_file.exists():
                    missing |= set(autoinstalled_file.read_text().splitlines())
                    self.logger.info(f"Adding new constraints to {autoinstalled_file}")
                autoinstalled_file.write_text("\n".join(sorted(missing)) + "\n")
            else:
                self.logger.warning(f"Missing constraints: {sorted(missing)}")
                console = Console()
                console.print(
                    f"You may want to add the following constraints to a file "
                    f"in the {self.constraints_d_folder}:"
                )
                console.print(*sorted(missing), sep="\n")
                console.print(
                    "Running  `plonex dependencies --persist` will do that for you."
                )
